---
- hosts: db
  become: yes

  tasks:
  - name: Ensure sqlite3 is installed.
    apt:
      name: sqlite3
      state: present

  - name: Ensure netstat is installed.
    apt:
      name: net-tools
      state: present

- hosts: app
  become: yes

  tasks:
  - name: Ensure nginx is installed.
    dnf:
      name: nginx
      state: present

  - name: Ensure nginx is running.
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Ensure netstat is installed.
    dnf:
      name: net-tools
      state: present